Repository jst-seminar-rostlab-tum/genomics.ai, pull requests merged in 2022-05, with the labels that each got.

#58 Feature/b 53 sprint 4 leave a team
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/routes/team/teamRouter.ts
  Backend/src/database/services/team.service.ts
Labels: feature, backend

#59 Feature/b 54 sprint 4 leave an institution
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/database/services/institution.service.ts
Labels: feature, backend

#67 Implemented /users route
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/routes/user/userRouter.ts
  Backend/src/database/services/user.service.ts
  Backend/src/swagger.json
Labels: feature, backend

#74 Feature/replace auth
  Frontend/src/components/DashboardContent/index.jsx
  Frontend/src/components/NavBar/NavBar.jsx
  Frontend/src/components/NavBar/old.jsx
  Frontend/src/components/NavigationBar/NavigationBar.jsx
  Frontend/src/components/NavigationBar/index.jsx
  Frontend/src/components/RegistrationForm/index.jsx
  Frontend/src/components/SettingsDropdown/index.jsx
  Frontend/src/components/Sidebar/index.jsx
  Frontend/src/components/general/HeaderView/index.jsx
  Frontend/src/views/Dashboard/index.jsx
  Frontend/src/views/Help/index.jsx
  Frontend/src/views/Home/index.jsx
  Frontend/src/views/InstitutionOverview/index.jsx
  Frontend/src/views/Settings/index.jsx
  Frontend/src/views/TeamOverview/index.jsx
  Frontend/src/views/TeamPage/index.jsx
  Frontend/src/views/UserProfile/index.jsx
Labels: Refactor

#76 Added missing await in atlasRouter and projectRouter
  Backend/src/API/REST/routes/atlas/atlasRouter.ts
  Backend/src/API/REST/routes/model/modelRouter.ts
Labels: bug, backend

#79 Use useAuth
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/DashboardContent/index.jsx
  Frontend/src/components/LoginForm/LoginForm.jsx
  Frontend/src/components/LoginForm/index.jsx
  Frontend/src/components/NavigationBar/NavigationBar.jsx
  Frontend/src/components/NavigationBar/index.jsx
  Frontend/src/components/ProfileImage/index.jsx
  Frontend/src/components/ProfileImage/profileImage.module.css
  Frontend/src/components/SettingsDropdown/index.jsx
  Frontend/src/components/Sidebar/index.jsx
  Frontend/src/components/general/upload/CropImage/canvasPreview.js
  Frontend/src/components/general/upload/CropImage/index.jsx
  Frontend/src/components/general/upload/CropImage/useDebounceEffect.js
  Frontend/src/components/general/upload/ImageUploadDialog/index.jsx
  Frontend/src/components/general/upload/InstitutionBackgroundImageUploadDialog/index.jsx
  Frontend/src/components/general/upload/InstitutionProfileImageUploadDialog/index.jsx
  Frontend/src/components/general/upload/ProfileImageUploadDialog/index.jsx
  Frontend/src/components/institutions/InstitutionCard/index.jsx
  Frontend/src/components/members/MemberCard/index.jsx
  Frontend/src/components/teams/TeamCard/index.jsx
  Frontend/src/components/teams/detail/TeamMemberList/index.jsx
  Frontend/src/shared/services/mock/institutions.js
  Frontend/src/shared/services/mock/members.js
  Frontend/src/shared/services/mock/profile.js
  Frontend/src/shared/services/mock/teams.js
  Frontend/src/shared/services/mock/user.js
  Frontend/src/shared/services/profile.js
  Frontend/src/shared/utils/common/constants.js
  Frontend/src/views/Settings/index.jsx
  Frontend/src/views/TeamPage/index.jsx
Labels: Refactor, Improvements

#68 added get endpoints for users institutions, teams and projects
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/API/REST/routes/project/projectRouter.ts
  Backend/src/API/REST/routes/team/teamRouter.ts
  Backend/src/database/services/institution.service.ts
  Backend/src/database/services/team.service.ts
  Backend/src/swagger.json
Labels: backend

#43 Add mapper functionality
  Frontend/src/components/Breadcrumb/index.jsx
  Frontend/src/components/Cards/AtlasCard.jsx
  Frontend/src/components/Cards/ModelCard.jsx
  Frontend/src/components/Filter/Filter.jsx
  Frontend/src/components/Filter/old.jsx
  Frontend/src/components/Mapper/index.jsx
  Frontend/src/components/Mapper/mapper.module.css
  Frontend/src/components/NavBar/NavBar.jsx
  Frontend/src/components/Tab/index.jsx
  Frontend/src/views/Explore/index.jsx
Labels: feature

#72 Feature/b 30 sprint 3 institution apis
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/middleware/validation.ts
  Backend/src/API/REST/routes/abort_processing.ts
  Backend/src/API/REST/routes/auth.ts
  Backend/src/API/REST/routes/file_download/results.ts
  Backend/src/API/REST/routes/file_upload/complete_upload.ts
  Backend/src/API/REST/routes/file_upload/start_upload.ts
  Backend/src/API/REST/routes/initiate_processing.ts
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/API/REST/routes/password_reset.ts
  Backend/src/API/REST/routes/register.ts
  Backend/src/API/REST/routes/resend_verification_link.ts
  Backend/src/API/REST/routes/update_profile.ts
  Backend/src/database/services/institution.service.ts
  Backend/src/swagger.json
Labels: backend

#47 Adapted multipart upload routes for new requirements
  Backend/dev/multipart_upload_script.js
  Backend/dev/scriptargs.json
  Backend/dev/test_file1.csv
  Backend/package-lock.json
  Backend/package.json
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/routes/abort_processing.ts
  Backend/src/API/REST/routes/file_download/results.ts
  Backend/src/API/REST/routes/file_upload/complete_upload.ts
  Backend/src/API/REST/routes/file_upload/get_upload_url.ts
  Backend/src/API/REST/routes/file_upload/start_upload.ts
  Backend/src/API/REST/routes/initiate_processing.ts
  Backend/src/API/REST/routes/project/projectRouter.ts
  Backend/src/database/dtos/project.dto.ts
  Backend/src/database/models/project.ts
  Backend/src/database/services/project.service.ts
  Backend/src/http_server/http_server.ts
  Backend/src/swagger.json
  Backend/tsconfig.json
Labels: feature, backend

#69 send email after invitation!
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/swagger.json
  Backend/src/views/mails/invitation_to_institution/html.html
  Backend/src/views/mails/invitation_to_institution/text.txt
Labels: feature, backend

#77 Feature/b 44 sprint 4 document apis
  Backend/src/swagger.json
Labels: documentation, backend

#86 Create Team with Institution
  Frontend/src/components/institutions/InstitutionCard/index.jsx
  Frontend/src/components/institutions/InstitutionChoice/index.jsx
  Frontend/src/components/institutions/InstitutionList/index.jsx
  Frontend/src/components/teams/overview/TeamCreationDialog/index.jsx
  Frontend/src/shared/services/Institution.service.js
  Frontend/src/shared/services/Team.service.js
  Frontend/src/shared/services/User.service.js
  Frontend/src/shared/services/mock/Institution.service.js
  Frontend/src/shared/services/mock/Team.service.js
Labels: enhancement

#91 Improving team mock data
  Frontend/src/components/jobs/JobCard/index.jsx
  Frontend/src/components/teams/TeamCard/index.jsx
  Frontend/src/components/teams/detail/TeamMemberList/index.jsx
  Frontend/src/components/teams/detail/TeamMemberMakeAdminButton/index.jsx
  Frontend/src/shared/services/mock/Job.service.js
  Frontend/src/shared/services/mock/Team.service.js
  Frontend/src/shared/services/mock/institutions.js
  Frontend/src/shared/services/mock/jobs.js
  Frontend/src/shared/services/mock/teams.js
  Frontend/src/views/TeamPage/index.jsx
Labels: enhancement

#100 Fix mock team creation
  Frontend/src/components/CustomButton/index.jsx
  Frontend/src/components/general/LoadingList/index.jsx
  Frontend/src/shared/services/mock/Institution.service.js
  Frontend/src/shared/services/mock/Team.service.js
  Frontend/src/views/TeamPage/index.jsx
Labels: Improvements

#101 Fix institution mock IDs not being Strings
  Frontend/src/shared/services/mock/Institution.service.js
Labels: Improvements

#111 Add alert for institution alert + minor bugfix
  Frontend/src/components/institutions/InstitutionCard/index.jsx
  Frontend/src/components/institutions/InstitutionCreationDialog/index.jsx
  Frontend/src/components/institutions/InstitutionInviteButton/index.jsx
  Frontend/src/shared/services/mock/Institution.service.js
  Frontend/src/shared/services/mock/Team.service.js
Labels: Improvements

#102 add mock institution descriptions + fix user id error
  Frontend/src/components/institutions/InstitutionCard/index.jsx
  Frontend/src/shared/services/mock/Institution.service.js
  Frontend/src/shared/services/mock/Team.service.js
Labels: Improvements

#105 Team desc update, make user admin of new teams/institutions
  Frontend/src/components/general/ListCard/index.jsx
  Frontend/src/components/teams/detail/TeamInviteButton/index.jsx
  Frontend/src/components/teams/detail/TeamMemberMakeAdminButton/index.jsx
  Frontend/src/components/teams/detail/TeamUserHeaderRight/index.jsx
  Frontend/src/shared/services/mock/Institution.service.js
  Frontend/src/shared/services/mock/Team.service.js
Labels: Improvements

#78 Feature/b 55 discuss double referencing
  Backend/src/API/REST/routes/team/teamRouter.ts
  Backend/src/database/models/team.ts
  Backend/src/database/services/team.service.ts
Labels: backend

#128 Feature/f2 explore refactor
  Frontend/package-lock.json
  Frontend/src/components/ExplorePageComponents/ExploreRoutes/index.jsx
  Frontend/src/components/Grids/AtlasesGrid/atlasesGrid.module.css
  Frontend/src/components/Grids/AtlasesGrid/index.jsx
  Frontend/src/components/Grids/ModelsGrid/index.jsx
  Frontend/src/components/Grids/ModelsGrid/modelsGrid.module.css
  Frontend/src/components/SearchPageComponents/Filter/GeneralFilter/index.jsx
  Frontend/src/components/SearchPageComponents/Filter/index.jsx
  Frontend/src/components/SearchPageComponents/SearchContent/index.jsx
  Frontend/src/components/SearchPageComponents/SearchTabs/index.jsx
  Frontend/src/shared/utils/filter.js
  Frontend/src/views/Explore/index.jsx
  Frontend/src/views/SearchPage/index.jsx
  Frontend/yarn.lock
Labels: help wanted, feature

#130 Feature/f2 scrollbar
  Frontend/src/components/Cards/ModelCard.jsx
  Frontend/src/components/Grids/AtlasesGrid/atlasesGrid.module.css
  Frontend/src/components/Grids/AtlasesGrid/index.jsx
  Frontend/src/components/Grids/ModelsGrid/index.jsx
  Frontend/src/components/Grids/ModelsGrid/modelsGrid.module.css
  Frontend/src/index.css
  Frontend/src/views/Explore/Explore.css
  Frontend/src/views/Explore/index.jsx
Labels: Improvements

#122 Community Page
  Frontend/src/components/CustomButton/index.jsx
  Frontend/src/components/DashboardContent/index.jsx
  Frontend/src/components/GeneMapper/plusIcon/index.jsx
  Frontend/src/components/Sidebar/index.jsx
  Frontend/src/components/general/ListCard/index.jsx
  Frontend/src/components/general/ListCard/listCard.module.css
  Frontend/src/components/general/PlusIcon/index.jsx
  Frontend/src/components/general/upload/ImageUploadDialog/index.jsx
  Frontend/src/components/general/upload/InstitutionBackgroundImageUploadDialog/index.jsx
  Frontend/src/components/general/upload/InstitutionProfileImageUploadDialog/index.jsx
  Frontend/src/components/general/upload/ProfileImageUploadDialog/index.jsx
  Frontend/src/components/institutionOverview/InstitutionCard/index.jsx
  Frontend/src/components/institutions/InstitutionCard/index.jsx
  Frontend/src/components/institutions/InstitutionChoice/index.jsx
  Frontend/src/components/institutions/InstitutionCreationDialog/index.jsx
  Frontend/src/components/institutions/InstitutionInviteButton/index.jsx
  Frontend/src/components/institutions/InstitutionLeaveButton/index.jsx
  Frontend/src/components/institutions/InstitutionMemberRemoveButton/index.jsx
  Frontend/src/components/institutions/InstitutionOverview/index.jsx
  Frontend/src/components/teams/TeamCard/index.jsx
  Frontend/src/components/teams/detail/TeamInviteButton/index.jsx
  Frontend/src/components/teams/detail/TeamJoinButton/index.jsx
  Frontend/src/components/teams/detail/TeamMemberMakeAdminButton/index.jsx
  Frontend/src/components/teams/detail/TeamMemberRemoveButton/index.jsx
  Frontend/src/components/teams/overview/TeamCreationDialog/index.jsx
  Frontend/src/components/teams/overview/TeamLeaveButton/index.jsx
  Frontend/src/components/teams/overview/TeamOverview/index.jsx
  Frontend/src/components/teams/overview/TeamOverview/teamOverview.module.css
  Frontend/src/shared/services/mock/Institution.service.js
  Frontend/src/shared/theme/colors.js
  Frontend/src/views/CommunityOverview/communityOverview.module.css
  Frontend/src/views/CommunityOverview/index.jsx
  Frontend/src/views/GeneMapper/Home/index.jsx
  Frontend/src/views/InstitutionOverview/index.jsx
  Frontend/src/views/InstitutionOverview/institutionOverview.module.css
  Frontend/src/views/InstitutionPage/index.jsx
  Frontend/src/views/TeamOverview/index.jsx
  Frontend/src/views/TeamOverview/teamOverview.module.css
Labels: feature

#118 Use New Button Styles
  Frontend/src/components/CustomButton/index.jsx
  Frontend/src/components/general/upload/ImageUploadDialog/index.jsx
  Frontend/src/components/general/upload/ProfileImageUploadDialog/index.jsx
  Frontend/src/components/institutionOverview/InstitutionCard/index.jsx
  Frontend/src/components/institutions/InstitutionCard/index.jsx
  Frontend/src/components/institutions/InstitutionChoice/index.jsx
  Frontend/src/components/institutions/InstitutionCreationDialog/index.jsx
  Frontend/src/components/institutions/InstitutionInviteButton/index.jsx
  Frontend/src/components/institutions/InstitutionLeaveButton/index.jsx
  Frontend/src/components/institutions/InstitutionMemberRemoveButton/index.jsx
  Frontend/src/components/teams/TeamCard/index.jsx
  Frontend/src/components/teams/detail/TeamInviteButton/index.jsx
  Frontend/src/components/teams/detail/TeamMemberMakeAdminButton/index.jsx
  Frontend/src/components/teams/detail/TeamMemberRemoveButton/index.jsx
  Frontend/src/components/teams/overview/TeamCreationDialog/index.jsx
  Frontend/src/components/teams/overview/TeamLeaveButton/index.jsx
  Frontend/src/shared/services/mock/Institution.service.js
  Frontend/src/views/InstitutionOverview/index.jsx
  Frontend/src/views/TeamOverview/index.jsx
Labels: Improvements

#123 Feature/join team
  Frontend/src/components/DashboardContent/index.jsx
  Frontend/src/components/SearchPageComponents/SearchContent/index.jsx
  Frontend/src/components/SearchPageComponents/SearchResultList/LabeledLink/index.jsx
  Frontend/src/components/SearchPageComponents/SearchResultList/ProjectCard/index.jsx
  Frontend/src/components/SearchPageComponents/SearchResultList/TeamCard/index.jsx
  Frontend/src/components/SearchPageComponents/SearchResultList/index.jsx
  Frontend/src/components/SearchPageComponents/SearchTabs/index.jsx
  Frontend/src/shared/services/Team.service.js
  Frontend/src/views/SearchPage/index.jsx
Labels: feature

#131 Finish splitting the swagger json into multiple files
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/middleware/validation.ts
  Backend/src/swagger.json
  Backend/src/swagger/load-swagger.ts
  Backend/swagger/paths/atlases.json
  Backend/swagger/paths/auth.json
  Backend/swagger/paths/authorize_user.json
  Backend/swagger/paths/file_download_results.json
  Backend/swagger/paths/file_upload.json
  Backend/swagger/paths/initiate_processing.json
  Backend/swagger/paths/institution.json
  Backend/swagger/paths/models.json
  Backend/swagger/paths/ownprojects.json
  Backend/swagger/paths/password_reset.json
  Backend/swagger/paths/profile.json
  Backend/swagger/paths/projects.json
  Backend/swagger/paths/register.json
  Backend/swagger/paths/resend.json
  Backend/swagger/paths/teams.json
  Backend/swagger/paths/update_profile.json
  Backend/swagger/paths/user-avatar.json
  Backend/swagger/paths/users.json
  Backend/swagger/swagger.json
Labels: backend

#127 bugfix in institution service
  Backend/src/database/services/institution.service.ts
  Backend/src/database/services/project.service.ts
Labels: bug, backend

#147 disable model card
  Frontend/src/components/Cards/ModelCard.jsx
  Frontend/src/components/Grids/ModelsGrid/index.jsx
  Frontend/src/views/Explore/index.jsx
Labels: feature

#141 Change on the endpoint creation of a team. Add an optional parameter …
  Backend/src/API/REST/routes/team/teamRouter.ts
  Backend/src/database/dtos/team.dto.ts
Labels: backend

#137 changes required in specific endpoints
  Backend/src/database/services/institution.service.ts
  Backend/src/database/services/team.service.ts
Labels: backend

#143 added new required update_institution endpoint and changed email to n…
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/database/services/institution.service.ts
  Backend/src/util/mailer.ts
  Backend/swagger/paths/institution.json
Labels: bug, feature, backend

#159 Implementation to invite a user to a team using his email
  Backend/src/API/REST/routes/team/teamRouter.ts
Labels: Improvements, feature, backend

#161 Feature/b 80 sprint 7 include adminids in memberids
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/API/REST/routes/team/teamRouter.ts
Labels: Improvements, backend

#148 Feature/b 74 implement recycle bin for projects
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/routes/file_upload/bucket_filepaths.ts
  Backend/src/API/REST/routes/file_upload/complete_upload.ts
  Backend/src/API/REST/routes/project/projectRouter.ts
  Backend/src/database/dtos/deletedProject.dto.ts
  Backend/src/database/dtos/project.dto.ts
  Backend/src/database/models/deleted_projects.ts
  Backend/src/database/services/deletedProject.service.ts
  Backend/src/database/services/institution.service.ts
  Backend/src/database/services/project.service.ts
  Backend/src/startup/init_env_vars.ts
  Backend/swagger/paths/cleanRecyclebin.json
  Backend/swagger/paths/deletedprojects.json
  Backend/swagger/paths/ownprojects.json
  Backend/swagger/paths/projects.json
  Backend/swagger/swagger.json
Labels: feature, backend

#172 Email links for joining into a team/institution
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/API/REST/routes/team/teamRouter.ts
  Backend/src/views/mails/invitation_to_institution/html.html
  Backend/src/views/mails/invitation_to_institution/text.txt
  Backend/src/views/mails/invitation_to_team/html.html
  Backend/src/views/mails/invitation_to_team/text.txt
Labels: Improvements, backend

#93 Feature/b 40 sprint 4 document apis
  Backend/docker-compose.yml
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/API/REST/routes/team/teamRouter.ts
  Backend/swagger/paths/institution.json
  Backend/swagger/paths/teams.json
Labels: documentation, backend

#175 Refactor/f2 landing page texts
  Frontend/src/components/Cards/AtlasCard.jsx
  Frontend/src/components/Grids/AtlasesGrid/index.jsx
  Frontend/src/components/WindowiOS/index.jsx
  Frontend/src/views/Explore/LearnMoreAtlas/index.jsx
  Frontend/src/views/Explore/index.jsx
  Frontend/src/views/Home/index.jsx
Labels: Improvements

#169 Fix / Delete profile cache on logout
  Frontend/src/components/Sidebar/index.jsx
  Frontend/src/components/general/upload/CropImage/index.jsx
  Frontend/src/shared/services/Profile.service.js
Labels: Improvements

#164 Improvement/Institution Admin Needed Explanation
  Frontend/src/components/institutions/InstitutionChoice/index.jsx
Labels: Improvements

#166 Feature/legal stuff
  Frontend/src/App.jsx
  Frontend/src/components/Footer/index.jsx
  Frontend/src/components/Sidebar/index.jsx
  Frontend/src/index.css
  Frontend/src/views/About/old.jsx
  Frontend/src/views/Contact/index.jsx
  Frontend/src/views/Docs/index.jsx
  Frontend/src/views/Explore/index.jsx
  Frontend/src/views/Imprint/index.jsx
  Frontend/src/views/Privacy/index.jsx
  Frontend/src/views/Terms/index.jsx
  Frontend/src/views/VisualizationPage/index.jsx
Labels: feature

#180 Connecting institution page to backend
  Frontend/src/components/institutions/InstitutionInviteButton/index.jsx
  Frontend/src/components/institutions/InstitutionMemberList/index.jsx
  Frontend/src/components/institutions/InstitutionMemberMakeAdminButton/index.jsx
  Frontend/src/components/institutions/InstitutionTeamList/institutionTeamList.module.css
  Frontend/src/shared/services/Institution.service.js
  Frontend/src/shared/services/User.service.js
  Frontend/src/views/InstitutionPage/index.jsx
  Frontend/src/views/InstitutionPage/institutionPage.module.css
  Frontend/src/views/UserProfile/index.jsx
Labels: Improvements

#192 Fix makeAdmin, removeAdmin and removeMember
  Frontend/src/components/institutions/InstitutionMemberMakeAdminButton/index.jsx
  Frontend/src/components/institutions/InstitutionMemberRemoveButton/index.jsx
  Frontend/src/shared/services/Institution.service.js
Labels: Improvements

#191 Fix for saving the edited description
  Frontend/src/shared/services/Institution.service.js
  Frontend/src/views/InstitutionPage/index.jsx
Labels: Improvements

#198 Improvement/improve loading error handling
  Frontend/src/components/general/upload/ImageUploadDialog/index.jsx
  Frontend/src/components/general/upload/InstitutionBackgroundImageUploadDialog/index.jsx
  Frontend/src/components/institutions/InstitutionOverview/index.jsx
  Frontend/src/components/teams/overview/TeamOverview/index.jsx
Labels: Improvements

#176 F2/forgot password and remember me
  Frontend/src/components/Input/Input.jsx
  Frontend/src/components/LoginForm/index.jsx
  Frontend/src/components/PasswordForgetForm/index.jsx
  Frontend/src/components/RegistrationForm/index.jsx
  Frontend/src/views/Home/index.jsx
  Frontend/src/views/PasswordResetPage/index.jsx
Labels: bug, Improvements

#199 Add email validation for institution invite
  Frontend/src/components/institutions/InstitutionInviteButton/index.jsx
Labels: Improvements

#185 Feature/b 68 privacy issues
  Backend/src/API/REST/routes/user/userRouter.ts
Labels: feature, backend

#206 Fix reload => profile info gone
  Frontend/src/shared/services/Profile.service.js
  Frontend/src/shared/services/SettingsLogic.js
  Frontend/src/views/Settings/index.jsx
Labels: Improvements

#188 Feature/b 81 sprint 7 include links to join inst
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/API/REST/routes/team/teamRouter.ts
Labels: backend

#208 Fix/user-by-id
  Backend/src/API/REST/routes/user/userRouter.ts
Labels: backend, bugfix

#217 Feature/b 72 add callback for ml results
  Backend/package-lock.json
  Backend/package.json
  Backend/src/API/REST/express_routes.ts
  Backend/src/API/REST/routes/file_download/results.ts
  Backend/src/API/REST/routes/file_upload/complete_upload.ts
  Backend/src/API/REST/routes/project/projectRouter.ts
  Backend/src/database/dtos/project_update_token.dto.ts
  Backend/src/database/models/project_update_token.ts
  Backend/src/database/services/project_update_token.service.ts
Labels: Improvements, backend

#218 Feature/b token based join
  Backend/src/API/REST/routes/institution/institutionRouter.ts
  Backend/src/API/REST/routes/team/teamRouter.ts
  Backend/src/database/dtos/joinToken.dto.ts
  Backend/src/database/models/join_token.ts
  Backend/src/database/services/joinToken.service.ts
  Backend/swagger/paths/institution.json
  Backend/swagger/paths/teams.json
Labels: Improvements, backend

#223 minor API usage adaption to a change for leaving teams/institutions
  Frontend/src/shared/services/Institution.service.js
  Frontend/src/shared/services/Team.service.js
Labels: bugfix

#224 Adapt profile page UI to look... better
  Frontend/src/views/Privacy/index.jsx
  Frontend/src/views/Settings/index.jsx
Labels: Improvements

#187 Add versioning
  Backend/src/API/REST/_rest_host.ts
  Backend/src/API/REST/express_routes.ts
  Backend/swagger/swagger.json
Labels: documentation, backend

#225 Improvement/community create and leave UI
  Frontend/src/components/institutions/InstitutionCreationDialog/index.jsx
  Frontend/src/components/institutions/InstitutionLeaveButton/index.jsx
  Frontend/src/components/teams/overview/TeamCreationDialog/index.jsx
  Frontend/src/components/teams/overview/TeamLeaveButton/index.jsx
Labels: Improvements
